### ISSUE TITLE
EasyAdapter is not being included in my project 

### ISSUE THREAD

**Issue by b3nnee** [Denive/EasyAdapter#2]
Hello, for some very awkward reason EasyAdapter is not being included in my project even after adding it via app's build.gradle - has the project moved from jitpack?

**Comment by b3nnee** [comment]
Noticed the recent update and tried again. No luck, EasyAdapter is not available for import.
You should try the sample app but import via the full github/jitpack dependency not your local files. 

Am I doing anything wrong?

**Comment by b3nnee** [comment]
I tried running the files as is from the repo and the result is the same...
![clipboard-1](https://user-images.githubusercontent.com/6034817/41502639-897653ea-71b6-11e8-9d4b-5b1f1e93d7b0.jpg)

**Comment by Oliinyk-Volodymyr** [comment]
I fixed library. You can check it

**Comment by b3nnee** [comment]
Thanks! Great Job BTW
